### ISSUE TITLE
Quick Sort Algorithm in C++

### ISSUE THREAD

**Issue by therealansh** [hacktoberfest2k20/DataStructures-and-Algorithms#11]
Recursive Quick Sort Algorithm. (Divide and Conquer Algorithm to sort a given array)

**Comment by s-ayush2903** [comment]
Please add some description as well

**Comment by AdarshSR28** [comment]
I want to work on this algorithm. Please assign it to me.

**Comment by s-ayush2903** [comment]
Great! Here you go

**Comment by s-ayush2903** [comment]
But please note that one can't be assigned to more than 2 issues at the same time

**Comment by therealansh** [comment]
So @s-ayush2903 can i do this one?

**Comment by AdarshSR28** [comment]
@s-ayush2903 Sure, will take care of it from next time.

**Comment by s-ayush2903** [comment]
> So @s-ayush2903 can i do this one?

* I'm really sorry @therealansh , but @AdarshSR28 claimed it few secs prior to your comment.
* To avoid mishappenings like this from now onwards, you may comment in the Issue description that you wanna work on the issue.
* For now, you may create a new issue or claim an unclaimed one to work on : )
