### ISSUE TITLE
Fractional Knapsack | C++ 

### ISSUE THREAD

**Issue by SSKale1** [hacktoberfest2k20/DataStructures-and-Algorithms#31]
## **`Fractional Knapsack Problem`** -

**Added Solution for the Fractional Knapsack Problem**

### Type of Issue -
- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

- [x] C++

**Comment by SSKale1** [comment]
I would like to contribute towards this Issue. Please assign me to it.

**Comment by s-ayush2903** [comment]
Go ahead!
