### ISSUE TITLE
Square Root Decomposition

### ISSUE THREAD

**Issue by Aditi-1400** [hacktoberfest2k20/DataStructures-and-Algorithms#36]
Implementation for Square Root Decomposition Technique to optimize Range Based Queries.

**Comment by Aditi-1400** [comment]
Hey, @s-ayush2903 Can I work on this?

**Comment by s-ayush2903** [comment]
Definitely, please go ahead!

**Comment by Aditi-1400** [comment]
Hey, I submitted the pull request!
