### ISSUE TITLE
Implement Depth First Search

### ISSUE THREAD

**Issue by AdityaSamantaroy** [hacktoberfest2k20/DataStructures-and-Algorithms#51]
Implement Depth First Search in a graph, using recursive approach.

**Comment by AdityaSamantaroy** [comment]
Can I take up this issue? @mayank64ce

**Comment by AdarshSR28** [comment]
I have assigned the work to you! :-) @AdityaSamantaroy

**Comment by mayank64ce** [comment]
@AdityaSamantaroy  Great! You are assigned.
