### ISSUE TITLE
Merge Sort Using CPP

### ISSUE THREAD

**Issue by AdarshSR28** [hacktoberfest2k20/DataStructures-and-Algorithms#7]

**Comment by unnatijain99** [comment]
@Akshat05-tech I want to add merge sort.

**Comment by AdarshSR28** [comment]
I want to work on this algorithm.

**Comment by unnatijain99** [comment]
@Akshat05-tech I can go for heap sort then?

**Comment by Akshat05-tech** [comment]
@unnatijain99 yes sure!! For that create a new issue regarding Heap Sort and there request for assigning to you..
