### ISSUE TITLE
Bubble Sort in java

### ISSUE THREAD

**Issue by Roshanpaswan** [hacktoberfest2k20/DataStructures-and-Algorithms#89]
iam going to add bubble sort in java

**Comment by s-ayush2903** [comment]
@Roshanpaswan Please comment first that you wanna work on this issue and only then open the PR : )

**Comment by vickyjsr** [comment]
i want to work on this issue please assign this to me !!
@s-ayush2903

**Comment by s-ayush2903** [comment]
@vickyjsr We have bubble sort in both cpp and java, you may take up another issue or create one or implement bubble sort in some different lang.

**Comment by s-ayush2903** [comment]
Bubble sort in java was implemented in #150.
