### ISSUE TITLE
Ackermann function

### ISSUE THREAD

**Issue by yogesh-kansal** [hacktoberfest2k20/DataStructures-and-Algorithms#92]
I want to work on this issue in c++,Please assign it to me

**Comment by s-ayush2903** [comment]
How do you plan to implement this? Give us your proposal

**Comment by yogesh-kansal** [comment]
I want do solve this using recursive approach that can be constructed from the definition of Ackernmann function.
Ackermann function is defind from non-negative numbers,as-
f(a,b) = b+1; if a=0,
f(a,b) =  f(a-1,1), if a>0 && b==0,
f(a,b) = f(a-1, f(a,b-1)); if a>0 &&b>0,
To solve this we can recurisvely call function with sufficient conditions.
Algorithm has time complexity of  O(aA(a, b)) to compute A(a, b).

**Comment by s-ayush2903** [comment]
Okay, fine I didn't want your code here in the issue, just wanted to know if you're aware of its implementation : ) 
Assigning

**Comment by yogesh-kansal** [comment]
yes,i am.
thankyou for assigning

**Comment by yogesh-kansal** [comment]
At which place should i place it or can i make a folder named maths

**Comment by s-ayush2903** [comment]
Hey @yogesh-kansal Please create it in the `Maths` folder itself, anyways thanks for asking, it just went off my mind

**Comment by yogesh-kansal** [comment]
@s-ayush2903  have a look at my PR #126

**Comment by s-ayush2903** [comment]
@yogesh-kansal This is not a very good practice to open multiple PRs that target the same issue, you could've made changes in this PR itself. Now I'm allowing it but I don't expect this in future
